---
title: "Lasso with cyclic coordinate descent"
author: "Jingyu Xu"
date: "09/13/2020"
output:
  html_document:
    code_folding: hide
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(pls)
library(tidyverse)
```

##Simulate data

```{r}
set.seed(111)
Sigma <- diag(c(8,2,6,4),4,4)
Sigma[1,2]=1.5
Sigma[2,1]=1.5#X1 and x2 are correlated 
X =MASS::mvrnorm(n=100, c(2, 2,2,3), Sigma)%>%as.data.frame()
colnames(X)=c("X1","X2","X3","X4")
X1 =X[,1]
X2 =X[,2]
X3 =X[,3]
X4= X[,4]
#generate Y
eps = rnorm(100,mean=0,sd=2)
Y = 2+8*X1+0.75*X4+eps
data=data.frame(X,Y)
```

##PLS by hand
```{r}
##construct pls direction
##denote m as the number of components which is no more than the number of predictors
pls_update_comp = function(X,Y,m){
     #X = robustHD::standardize(X)
     X= as.matrix(X)
     Y = as.matrix(Y)
     p = ncol(X)
     n = nrow(Y)
     Z = matrix(0,n,m)

   for (i in 1:m){   
   #Z[,i]= X%*%crossprod(X,Y)
    for(k in 1:p){
      theta=as.numeric(crossprod(X[,k],Y))*X[,k]
      Z[,i]=Z[,i]+theta
    }
    #update x
   for(j in 1:p){
     X[,j]=X[,j]-(as.numeric(crossprod(Z[,i],X[,j])/crossprod(Z[,i],Z[,i])))*Z[,i]
   }
   }
     return(Z)
}

##do regression
pls_regression= function(X,Y,m){
  Z=pls_update_comp(X,Y,m)
  Y_predict= rep(0,nrow(Y))
  for (i in 1:m) {
    proj = crossprod(Z[,i],Y)/crossprod(Z[,i])
    Y_predict = Y_predict+(as.numeric(proj)*Z[,i])
  }
  return(Y_predict)
}

```



##compare with R package
```{r}
X=as.matrix(X)
Y=as.matrix(Y)
R_pls = plsr(Y~., data = data,scale=F)
R_pls$ncomp # four components
self_pls = pls_update_comp(X,Y,4)
self_fitted = pls_regression(X,Y,4)

##check the fitted values
#In terms of RMSE
##R 
sqrt(crossprod(R_pls$fitted.values-as.numeric(Y))/100)
##self
sqrt(crossprod(self_fitted-as.numeric(Y))/100)
##check the direction of compositions
R_d = R_pls$scores
self_d=self_pls
direction=rep(0,ncol(X))
for (i in 1:4) {
  c = crossprod(R_d[,i],self_d[,i])/sqrt(crossprod(R_d[,i])*crossprod(self_d[,i]))
  direction[i]=c
}


```

